# Generated by Django 3.1.7 on 2021-04-05 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn_13', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publish_date', models.CharField(max_length=100, null=True)),
                ('publishers', models.CharField(max_length=100, null=True)),
                ('isbn_10', models.CharField(max_length=20, null=True)),
                ('img_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cached_Book',
            fields=[
                ('isbn_13', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publish_date', models.CharField(max_length=100, null=True)),
                ('publishers', models.CharField(max_length=100, null=True)),
                ('isbn_10', models.CharField(max_length=20, null=True)),
                ('img_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isbn_13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.cached_book')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookID', models.BigIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('isbn_13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.book')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_1_status', models.CharField(choices=[('pp', 'Preparing my book.'), ('ms', 'My book is sent.'), ('ys', 'Your book is sent back.'), ('cp', 'Complete')], max_length=2)),
                ('user_2_status', models.CharField(choices=[('pp', 'Preparing my book.'), ('ms', 'My book is sent.'), ('ys', 'Your book is sent back.'), ('cp', 'Complete')], max_length=2)),
                ('exchange_active', models.BooleanField(default=True)),
                ('book_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_book_1', to='myApp.user_book')),
                ('book_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_book_2', to='myApp.user_book')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('denied', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('book_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_book_1', to='myApp.user_book')),
                ('book_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_book_2', to='myApp.user_book')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cached_book',
            name='on_wishlist',
            field=models.ManyToManyField(through='myApp.Wish_List', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='owned_by',
            field=models.ManyToManyField(through='myApp.User_Book', to=settings.AUTH_USER_MODEL),
        ),
    ]
