# Generated by Django 3.1.7 on 2021-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_book',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_book',
            name='bookID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
