# Generated by Django 3.1.7 on 2021-03-23 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn_13', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publish_date', models.IntegerField(null=True)),
                ('publishers', models.CharField(max_length=100, null=True)),
                ('isbn_10', models.IntegerField(null=True)),
                ('img_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cached_Book',
            fields=[
                ('isbn_13', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publish_date', models.IntegerField(null=True)),
                ('publishers', models.CharField(max_length=100, null=True)),
                ('isbn_10', models.IntegerField(null=True)),
                ('img_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('isbn_13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.book')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
