# Generated by Django 3.1.7 on 2021-03-24 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0002_book_cached_book_user_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_book',
            old_name='BookID',
            new_name='bookID',
        ),
        migrations.AddField(
            model_name='book',
            name='owned_by',
            field=models.ManyToManyField(through='myApp.User_Book', to=settings.AUTH_USER_MODEL),
        ),
    ]
