# Generated by Django 3.1.7 on 2021-03-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_book_cached_book_user_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cached_book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cached_book',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='cached_book',
            name='isbn_10',
        ),
        migrations.RemoveField(
            model_name='cached_book',
            name='isbn_13',
        ),
        migrations.RemoveField(
            model_name='cached_book',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='cached_book',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='cached_book',
            name='title',
        ),
        migrations.AddField(
            model_name='cached_book',
            name='book_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myApp.book'),
            preserve_default=False,
        ),
    ]
