# Generated by Django 3.1.7 on 2021-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210405_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cached_book',
            name='isbn_10',
            field=models.BigIntegerField(null=True),
        ),
    ]
