# Generated by Django 3.1.7 on 2021-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210405_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cached_book',
            name='isbn_10',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
