# Generated by Django 3.1.7 on 2021-03-24 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0004_auto_20210324_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.cached_book')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cached_book',
            name='on_wishlist',
            field=models.ManyToManyField(through='myApp.Wish_List', to=settings.AUTH_USER_MODEL),
        ),
    ]
