# Generated by Django 3.1.7 on 2021-03-24 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0005_auto_20210324_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1_status', models.CharField(choices=[('pp', 'Preparing my book.'), ('ms', 'My book is sent.'), ('ys', 'Your book is sent back.'), ('cp', 'Complete')], max_length=2)),
                ('user_2_status', models.CharField(choices=[('pp', 'Preparing my book.'), ('ms', 'My book is sent.'), ('ys', 'Your book is sent back.'), ('cp', 'Complete')], max_length=2)),
                ('exchange_active', models.BooleanField(default=True)),
                ('book_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_book_1', to='myApp.book')),
                ('book_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_book_2', to='myApp.book')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('book_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.book')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
