# Generated by Django 3.1.7 on 2021-03-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210324_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='canceled',
            new_name='denied',
        ),
    ]
