# Generated by Django 3.1.7 on 2021-03-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210325_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='book_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_book_1', to='myApp.book'),
        ),
        migrations.AlterField(
            model_name='request',
            name='book_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_book_2', to='myApp.book'),
        ),
    ]
