# Generated by Django 3.1.7 on 2021-03-26 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20210325_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='book_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_book_1', to='myApp.user_book'),
        ),
        migrations.AlterField(
            model_name='status',
            name='book_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_book_2', to='myApp.user_book'),
        ),
    ]
