# Generated by Django 3.1.7 on 2021-03-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20210326_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='book_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_book_1', to='myApp.user_book'),
        ),
        migrations.AlterField(
            model_name='request',
            name='book_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_book_2', to='myApp.user_book'),
        ),
    ]
