# Generated by Django 3.1.7 on 2021-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20210327_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cached_book',
            name='isbn_13',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
